services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: bank_rest
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5433:5432
    restart: unless-stopped


volumes:
  postgres:
    driver: local